database:
  host: localhost
  user: CHANGETHIS
  password: CHANGETHIS
  database: CHANGETHIS
  tableprefix: cubeQuest
generateDailyQuests: false
payRewards: false
globalDataChannelName: CubeQuest
dailyQuestStreakRewards:
  7:
    ==: de.iani.cubequest.Reward
    cubes: 0
    xp: 0
    questPoints: 25
    items:
    - ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: BOOK
      amount: 2
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Mysteriöses Drei-Tagebuch"}],"text":""}'
        loc-name: '{"extra":[{"text":"headcase_case_dailyquest"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Rechtsklicken um ein zufälliges"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Belohnungsitem zu erhalten!"}],"text":""}'
        - '{"text":"Als Belohnung von einer Dailyquest erhalten."}'
        enchants:
          DURABILITY: 1
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
  14:
    ==: de.iani.cubequest.Reward
    cubes: 0
    xp: 0
    questPoints: 50
    items:
    - ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: BOOK
      amount: 5
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Mysteriöses Drei-Tagebuch"}],"text":""}'
        loc-name: '{"extra":[{"text":"headcase_case_dailyquest"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Rechtsklicken um ein zufälliges"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Belohnungsitem zu erhalten!"}],"text":""}'
        - '{"text":"Als Belohnung von einer Dailyquest erhalten."}'
        enchants:
          DURABILITY: 1
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
  21:
    ==: de.iani.cubequest.Reward
    cubes: 0
    xp: 0
    questPoints: 75
    items:
    - ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: BOOK
      amount: 7
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Mysteriöses Drei-Tagebuch"}],"text":""}'
        loc-name: '{"extra":[{"text":"headcase_case_dailyquest"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Rechtsklicken um ein zufälliges"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Belohnungsitem zu erhalten!"}],"text":""}'
        - '{"text":"Als Belohnung von einer Dailyquest erhalten."}'
        enchants:
          DURABILITY: 1
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
repeatingDailyQuestStreakRewards:
  begin: 28
  interval: 7
  reward: 
    ==: de.iani.cubequest.Reward
    cubes: 0
    xp: 0
    questPoints: 100
    items:
    - ==: org.bukkit.inventory.ItemStack
      v: 3218
      type: BOOK
      amount: 10
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"blue","text":"Mysteriöses Drei-Tagebuch"}],"text":""}'
        loc-name: '{"extra":[{"text":"headcase_case_dailyquest"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Rechtsklicken um ein zufälliges"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Belohnungsitem zu erhalten!"}],"text":""}'
        - '{"text":"Als Belohnung von einer Dailyquest erhalten."}'
        enchants:
          DURABILITY: 1
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
