database:
  host: localhost
  user: CHANGETHIS
  password: CHANGETHIS
  database: CHANGETHIS
  tableprefix: cubeQuest
generateDailyQuests: false
payRewards: false
globalDataChannelName: CubeQuest
